#!/bin/bash
echo "📤 Pushing to GitHub..."
echo ""
echo "1. 创建 GitHub 仓库:"
echo "   浏览器打开: https://github.com/new"
echo "   仓库名: polymarket-arbitrage-bot"
echo "   不要勾选 Add a README file"
echo "   点击 Create repository"
echo ""
echo "2. 获取 Token (如果需要):"
echo "   https://github.com/settings/tokens"
echo "   生成 new token (classic)"
echo "   勾选 repo"
echo ""
echo "3. 运行以下命令:"
echo ""
echo "cd /root/polymarket-bots/polymarket-arbitrage-bot"
echo "git remote set-url origin https://YOUR_TOKEN@github.com/Mstrcapital/polymarket-arbitrage-bot.git"
echo "git push -u origin main"
echo ""
echo "或者直接运行:"
echo "gh repo create polymarket-arbitrage-bot --public --source=. --push"
